---
title: "Practice Exercises"
output: html_document
date: "`r format(Sys.time(), '%d %B, %Y')`"
editor_options: 
  chunk_output_type: console
---

# Basic R calculation

```{r}
2+2

5-3

4+2*(10/2)

sqrt(9)

a <- c(2, 3, 4)

2*a
```


# Install and load libraries

```{r}
rm(list=ls())
library(here) #set directory
library(datasets) #build in datasets
library(tidyverse) #The tidyverse is an opinionated collection of R packages designed for data science
```

# Iris dataset

Upload the data as a built-in dataset.

```{r}
data(iris)
help(iris)
names(iris) <- tolower(names(iris)) #This is to use lowercase names.
names(iris)
dim(iris)
head(iris)
tail(iris)
summary(iris)
str(iris)
table(iris$species)
```

Upload the data as an external dataset.

```{r}
dt <- read.csv(here("data", "iris.csv"))
names(iris)
dim(iris)
head(iris)
tail(iris)
summary(iris)
str(iris)
table(iris$species)
```

```{r}
# filter() the data for species virginica
virginica <- filter(iris, species == "virginica")
dim(virginica)
head(virginica) # This dispalys the first six rows
```

```{r}
sepalLength6 <- filter(iris, species == "virginica", sepal.length > 6)
dim(sepalLength6)
tail(sepalLength6) # compare this to head()
```

```{r}
# select() the specified columns
selected <- iris %>% select( sepal.length, sepal.width, petal.length)
# select all columns from sepal.length to petal.length
selected2 <- iris %>% select(sepal.length:petal.length)
head(selected, 3)
head(selected2, 3)
```

```{r}
# create a new column that stores logical values for sepal.width greater than half of sepal.length
newCol <- iris %>% mutate(greater.half = sepal.width > 0.5 * sepal.length)
newCol$half_sepal_length <- 0.5 * newCol$sepal.length
tail(newCol)
```

## Visualization

```{r}
plot(iris)
# use ?plot to read more about other arguments
plot(iris$sepal.width, iris$sepal.length)
```

```{r}
# ?hist will give you details on more arguments
hist(iris$sepal.width)
```

```{r}
# library(ggplot2)
ggplot(iris, aes(x = sepal.length, y = sepal.width)) + geom_point()
```

```{r}
ggplot(iris, aes(x = sepal.length, y = sepal.width, colour = species)) + geom_point()
```

```{r}
ggplot(iris, aes(x = sepal.length, fill = species)) + geom_histogram()
```

```{r}
ggplot(iris, aes(x = sepal.length, colour = species)) + geom_density()
```

```{r}
ggplot(iris, 
       aes(x = species, y = sepal.length)) + 
        geom_boxplot()
```

```{r}
ggplot(iris, aes(x = sepal.length, y = sepal.width)) + geom_point() + geom_smooth()
```

```{r}
ggplot(iris, aes(x = sepal.length, y = sepal.width)) + geom_point() + geom_smooth(aes(colour = species))
```

```{r}
base <- ggplot(iris, aes(x = sepal.length, y = sepal.width)) + geom_point()

base + facet_wrap(~species)
```

## Inference

```{r}
petal.length.aov <- aov(formula = petal.length ~ species, data = iris)
summary(petal.length.aov)
```

Safe the results from the ANOVA
```{r}
sink(file = "output/petal-length-anova.txt")
summary(object = petal.length.aov)
sink()
```

